import { StyleSheet } from '@react-pdf/renderer';

export const palette = {
  text: '#0f172a',
  muted: '#3f3f46',
  subtle: '#52525b',
  border: '#d4d4d8',
  borderStrong: '#0f172a',
  surface: '#ffffff',
  softSurface: '#f4f4f5',
  warn: '#92400e',
  warnSurface: '#fef3c7',
  accentSurface: '#eef2ff',
  negative: '#9f1239',
};

export const styles = StyleSheet.create({
  page: {
    fontFamily: 'Nunito Sans',
    fontSize: 10,
    color: palette.text,
    paddingTop: 44,
    paddingBottom: 60,
    paddingHorizontal: 44,
    backgroundColor: palette.surface,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  headerLeft: {
    flexDirection: 'column',
    flexShrink: 1,
    paddingRight: 24,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  eyebrow: {
    fontSize: 8,
    letterSpacing: 1.4,
    color: palette.subtle,
    textTransform: 'uppercase',
    marginBottom: 4,
    fontWeight: 600,
  },
  title: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 10,
    color: palette.muted,
    fontWeight: 500,
  },
  metaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    width: 220,
    columnGap: 12,
    rowGap: 6,
  },
  metaItem: {
    alignItems: 'flex-end',
    width: 104,
    marginBottom: 0,
  },
  metaLabel: {
    fontSize: 7.5,
    letterSpacing: 1.2,
    color: palette.subtle,
    textTransform: 'uppercase',
    marginBottom: 2,
    fontWeight: 600,
  },
  metaValue: {
    fontSize: 10.5,
    fontWeight: 700,
  },
  metaValueMono: {
    fontSize: 10.5,
    fontWeight: 700,
    fontFamily: 'Nunito Sans',
  },
  banner: {
    marginTop: 6,
    marginBottom: 18,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 3,
    backgroundColor: palette.warnSurface,
    color: palette.warn,
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  divider: {
    borderBottomWidth: 0.5,
    borderBottomColor: palette.border,
    marginVertical: 14,
  },
  parties: {
    flexDirection: 'row',
    gap: 24,
    marginTop: 6,
  },
  partyCol: {
    flexGrow: 1,
    flexBasis: 0,
  },
  partyEyebrow: {
    fontSize: 7.5,
    letterSpacing: 1.2,
    color: palette.subtle,
    textTransform: 'uppercase',
    marginBottom: 6,
    fontWeight: 600,
  },
  partyName: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 3,
  },
  partyLine: {
    fontSize: 9.5,
    color: palette.muted,
    marginBottom: 1,
    fontWeight: 500,
  },
  bankBlock: {
    marginTop: 18,
    padding: 14,
    borderRadius: 4,
    backgroundColor: palette.softSurface,
    borderWidth: 0.5,
    borderColor: palette.border,
  },
  bankTitle: {
    fontSize: 8,
    letterSpacing: 1.4,
    color: palette.subtle,
    textTransform: 'uppercase',
    fontWeight: 600,
    marginBottom: 8,
  },
  bankGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  bankItem: {
    flexBasis: '48%',
    flexGrow: 1,
  },
  bankLabel: {
    fontSize: 7.5,
    color: palette.subtle,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
    marginBottom: 2,
    fontWeight: 600,
  },
  bankValue: {
    fontSize: 10,
    color: palette.text,
    fontWeight: 600,
  },
  sectionEyebrow: {
    fontSize: 7.5,
    letterSpacing: 1.2,
    color: palette.subtle,
    textTransform: 'uppercase',
    marginBottom: 4,
    fontWeight: 600,
  },
  periodRow: {
    flexDirection: 'row',
    gap: 24,
    marginTop: 6,
  },
  periodItem: {
    flex: 1,
  },
  periodValue: {
    fontSize: 10,
    fontWeight: 600,
  },
  heroBlock: {
    marginTop: 18,
    padding: 18,
    borderRadius: 6,
    backgroundColor: palette.softSurface,
    borderWidth: 0.5,
    borderColor: palette.border,
    alignItems: 'flex-end',
  },
  heroEyebrow: {
    fontSize: 8,
    letterSpacing: 1.4,
    color: palette.subtle,
    textTransform: 'uppercase',
    fontWeight: 600,
    marginBottom: 4,
  },
  heroAmount: {
    fontSize: 28,
    fontWeight: 700,
    color: palette.text,
    letterSpacing: -0.4,
  },
  heroAmountNegative: {
    color: palette.negative,
  },
  heroReference: {
    marginTop: 6,
    fontSize: 10,
    color: palette.muted,
    fontWeight: 500,
  },
  disclosure: {
    marginTop: 10,
    fontSize: 9,
    color: palette.muted,
    fontWeight: 500,
  },
  negativeValue: {
    color: palette.negative,
  },
  originalRef: {
    marginTop: 18,
    padding: 12,
    borderRadius: 4,
    borderWidth: 0.5,
    borderColor: palette.warn,
    backgroundColor: palette.warnSurface,
  },
  originalRefTitle: {
    fontSize: 9,
    fontWeight: 700,
    color: palette.warn,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  originalRefGrid: {
    flexDirection: 'row',
    gap: 20,
  },
  originalRefItem: {
    flex: 1,
  },
  originalRefLabel: {
    fontSize: 7.5,
    color: palette.muted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 2,
    fontWeight: 600,
  },
  originalRefValue: {
    fontSize: 10,
    fontWeight: 600,
  },
  notes: {
    marginTop: 20,
    paddingTop: 10,
    borderTopWidth: 0.5,
    borderTopColor: palette.border,
    fontSize: 10,
    color: palette.muted,
    lineHeight: 1.4,
    fontWeight: 500,
  },
  signatureCenter: {
    marginTop: 36,
    alignItems: 'center',
  },
  signatureName: {
    fontSize: 11,
    fontWeight: 700,
    color: palette.text,
    textAlign: 'center',
  },
  signatureDate: {
    fontSize: 9,
    color: palette.muted,
    marginTop: 2,
    textAlign: 'center',
    fontWeight: 500,
  },
  footerCenter: {
    position: 'absolute',
    bottom: 24,
    left: 44,
    right: 44,
    alignItems: 'flex-start',
  },
  footerLink: {
    fontSize: 8.5,
    color: palette.muted,
    textDecoration: 'none',
    fontWeight: 500,
  },
  footerLinkAccent: {
    color: palette.text,
    fontWeight: 600,
  },
  footerPage: {
    position: 'absolute',
    bottom: 24,
    right: 44,
    fontSize: 8.5,
    color: palette.subtle,
    fontWeight: 500,
  },
});
